version: '3.9'

services:
  scrapy:
    build: ./Scrapy
    depends_on:
      - mongo
    command: tail -f /dev/null  #Désactive l'exécution automatique

  api:
    build: ./Api
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: changeme

    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
